CREATE DATABASE IF NOT EXISTS gestaoFinanceira

USE gestaoFinanceira

CREATE TABLE IF NOT EXISTS Users (
    UserID SERIAL PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
)
